Move more code into prepare_bf_base

diff --git a/bin/p3wm b/bin/p3wm
--- a/bin/p3wm
+++ b/bin/p3wm
@@ -122,8 +122,31 @@ verify_args() {
 
 prepare_bf_base() {
   bf_local="$1"
+
+  pkg_name="$(pacman -Qoq "$bf_local")"
+
+  ver_tuple="$(get_ver_tuple "$pkg_name")"
+  oldver="${ver_tuple% *}"
+
+  arch="$(get_pkg_arch "$pkg_name")"
+
+  pkg_cached=""
+  mapfile -t cache_dirs < <(pacman-conf CacheDir)
+  for cache_dir in "${cache_dirs[@]}"; do
+    for f in "$cache_dir/$pkg_name-$oldver-$arch".pkg.* ; do
+      pkg_cached="$f"
+    done
+  done
+
+  if [[ -z $pkg_cached ]]; then
+    echo "Unable to find package ‘$pkg_name-$oldver-$arch’ in cache"
+    exit 2
+  fi
+
   basename_=$(basename "$bf_local")
   bf_base="$(mktmp ".base.$basename_")"
+  bf_id="${bf_local#/}"
+  tar xOf "$pkg_cached" "$bf_id" -- > "$bf_base"
 
   echo -n "$bf_base"
 }
@@ -142,33 +165,13 @@ main() {
 
   bf_pacnew="$(realpath "$1")"
   bf_local="${bf_pacnew%.pacnew}"
-  pkg_name="$(pacman -Qoq "$bf_local")"
+
   if [[ $bf_pacnew = "$bf_local" ]]; then
     echo 'You done messed up'
     exit 3
   fi
 
-  ver_tuple="$(get_ver_tuple "$pkg_name")"
-  oldver="${ver_tuple% *}"
-
-  arch="$(get_pkg_arch "$pkg_name")"
   bf_base="$(prepare_bf_base "$bf_local")"
-
-  pkg_cached=""
-  mapfile -t cache_dirs < <(pacman-conf CacheDir)
-  for cache_dir in "${cache_dirs[@]}"; do
-    for f in "$cache_dir/$pkg_name-$oldver-$arch".pkg.* ; do
-      pkg_cached="$f"
-    done
-  done
-
-  if [[ -z $pkg_cached ]]; then
-    echo "Unable to find package ‘$pkg_name-$oldver-$arch’ in cache"
-    exit 2
-  fi
-
-  bf_id="${bf_local#/}"
-  tar xOf "$pkg_cached" "$bf_id" -- > "$bf_base"
   bf_merged="$(mktmp ".merged.$basename")"
 
   if "$P3WM_MERGE_TOOL" "$bf_local" "$bf_base" "$bf_pacnew" > "$bf_merged"
